version: "3"

services:
  edge:
    build: ./edge
    depends_on:
      - fog
    environment:
      - PYTHONUNBUFFERED=1
      - TF_ENABLE_ONEDNN_OPTS=0

  fog:
    build: ./fog
    cap_add:
      - NET_ADMIN
    ports:
      - "5000:5000"
    depends_on:
      - cloud
    environment:
      - PYTHONUNBUFFERED=1

  cloud:
    build: ./cloud
    ports:
      - "6001:6001"
    volumes:
      - ./logs:/app/logs      
    environment:
      - PYTHONUNBUFFERED=1